//! The catalog packs.
//!
//! Each pack is a parameter set, not a folder of bitmaps. That is the whole
//! trick behind PRD §7.1: the artwork is vector code, the colour is applied at
//! apply time, and a catalog that looks enormous costs the installer nothing.
//!
//! Names are deliberately generic. No pack is named after a platform, console,
//! game or company — PRD §15.3 rules out third-party marks, and "the retro one"
//! does not need somebody else's trademark to read as retro.

use crate::packs::art::{Fill, Form, Reticle, Style, Treatment};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum Category {
    Precision,
    Neon,
    Minimal,
    Retro,
    Gaming,
    Animated,
    Fun,
}

impl Category {
    pub const fn as_str(self) -> &'static str {
        match self {
            Category::Precision => "PRECISION",
            Category::Neon => "NEON",
            Category::Minimal => "MINIMAL",
            Category::Retro => "RETRO",
            Category::Gaming => "GAMING",
            Category::Animated => "ANIMATED",
            Category::Fun => "FUN",
        }
    }
}

#[derive(Debug, Clone)]
pub struct PackDef {
    pub id: &'static str,
    pub name: &'static str,
    pub category: Category,
    pub style: Style,
    /// Animated packs ship `.ani` for the two roles Windows animates.
    pub animated: bool,
    /// The colour the pack looks best in before the user picks their own.
    pub default_tint: &'static str,
}

struct Builder {
    style: Style,
}

/// The vocabulary for defining a pack.
///
/// Most of these setters have no caller now that the generated catalog is a
/// single pack, and they are kept deliberately. They are not leftovers — they
/// are the only way a pack gets authored, and `art.rs` still renders every
/// `Form`, `Fill` and `Treatment` they set. Deleting them to satisfy the
/// dead-code lint would delete the ability to add a cursor to this app, in
/// exchange for nothing: none of it is compiled into a shipped binary that does
/// not use it.
#[allow(dead_code)]
impl Builder {
    fn new() -> Self {
        Self {
            style: Style::default(),
        }
    }
    fn form(mut self, form: Form) -> Self {
        self.style.form = form;
        self
    }
    fn fill(mut self, fill: Fill) -> Self {
        self.style.fill = fill;
        self
    }
    fn reticle(mut self, reticle: Reticle) -> Self {
        self.style.reticle = reticle;
        self
    }
    fn weight(mut self, weight: f32) -> Self {
        self.style.weight = weight;
        self
    }
    fn glow(mut self, glow: f32) -> Self {
        self.style.glow = glow;
        self
    }
    fn round(mut self) -> Self {
        self.style.round_joins = true;
        self
    }
    fn opacity(mut self, opacity: f32) -> Self {
        self.style.opacity = opacity;
        self
    }
    fn scale(mut self, scale: f32) -> Self {
        self.style.scale = scale;
        self
    }
    fn treat(mut self, treatment: Treatment) -> Self {
        self.style.treatment = treatment;
        self
    }
    fn done(self) -> Style {
        self.style
    }
}

fn pack(
    id: &'static str,
    name: &'static str,
    category: Category,
    style: Style,
    default_tint: &'static str,
) -> PackDef {
    PackDef {
        id,
        name,
        category,
        style,
        animated: matches!(category, Category::Animated),
        default_tint,
    }
}

/// Every pack, in catalog order.
pub fn all() -> Vec<PackDef> {
    use Category::*;
    use Reticle::*;

    // One pack, and it is not here to be browsed.
    //
    // There were 291, generated by combining about twenty base forms with
    // reticles, fills, treatments and colours. That is what they looked like: the
    // same handful of arrows under 291 different names, which is a catalog only
    // by the count. They are gone.
    //
    // This one stays because Blend needs it. An imported pack almost always
    // defines one or two roles -- an arrow, sometimes a hand -- and the other
    // fifteen have to come from somewhere. Without a complete pack behind them,
    // the moment the machine does anything (a copy, a download, an app starting)
    // the pointer turns back into a stock Windows one, which reads as the cursor
    // having reverted. It is deliberately the plainest thing in the set, because
    // its job is to be unnoticed next to somebody else's artwork.
    vec![pack(
        "precision-gap-cross",
        "GAP-CROSS",
        Precision,
        Builder::new().reticle(GapCross).done(),
        "#EDF1F7",
    )]
}

pub fn find(id: &str) -> Option<PackDef> {
    all().into_iter().find(|pack| pack.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// The generated catalog is one pack, and that one has a job.
    ///
    /// This used to demand at least 64 and exactly 291. Both are gone on
    /// purpose: 291 packs built by permuting twenty forms against reticles,
    /// fills, treatments and colours is a catalog by the count and not by the
    /// content, and it was cut back to nothing but the pack Blend needs.
    ///
    /// What is worth asserting now is that the pack Blend needs still exists,
    /// under the id everything defaults to. Losing it does not fail a build —
    /// it fails at apply time, on a user's machine, as fifteen stock Windows
    /// pointers appearing behind their cursor.
    #[test]
    fn the_blend_base_is_present_under_the_id_everything_expects() {
        let packs = all();
        assert_eq!(packs.len(), 1, "the generated catalog is deliberately one pack");
        assert!(
            find("precision-gap-cross").is_some(),
            "the default blend pack is missing; every imported cursor depends on it"
        );
        assert_eq!(
            crate::state::settings::Settings::default().blend_pack,
            "precision-gap-cross",
            "the default blend pack setting names a pack that does not exist"
        );
    }

    /// Colour is a setting, not a design.
    ///
    /// Two packs with identical geometry and different default tints are the
    /// same cursor twice. Shipping both floods a category with what looks like
    /// repetition and buries the designs that genuinely differ — the user can
    /// already recolour anything, so the second entry earns nothing.
    #[test]
    fn no_two_packs_are_the_same_design_in_a_different_colour() {
        use std::collections::HashMap;

        let packs = all();
        let mut seen: HashMap<String, &'static str> = HashMap::new();
        let mut clashes = Vec::new();

        for pack in &packs {
            let s = &pack.style;
            // Everything that changes a pixel, and nothing that does not.
            let signature = format!(
                "{:?}|{:?}|{:?}|{:?}|{:.2}|{:.2}|{}|{:.2}|{:.2}",
                s.form,
                s.fill,
                s.reticle,
                s.treatment,
                s.weight,
                s.glow,
                s.round_joins,
                s.opacity,
                s.scale
            );
            if let Some(first) = seen.insert(signature.clone(), pack.name) {
                clashes.push(format!("{} is {} in another colour", pack.name, first));
            }
        }

        assert!(
            clashes.is_empty(),
            "{} colour-only duplicate(s):\n  {}",
            clashes.len(),
            clashes.join("\n  ")
        );
    }

    #[test]
    fn ids_and_names_are_unique_and_slug_safe() {
        let packs = all();
        let ids: HashSet<_> = packs.iter().map(|p| p.id).collect();
        let names: HashSet<_> = packs.iter().map(|p| p.name).collect();
        assert_eq!(ids.len(), packs.len(), "duplicate pack id");
        assert_eq!(names.len(), packs.len(), "duplicate pack name");

        for pack in &packs {
            assert!(
                pack.id
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'),
                "{} is not a safe directory name",
                pack.id
            );
            assert!(crate::util::parse_hex_color(pack.default_tint).is_some());
        }
    }

    /// The category filter must only offer categories that have packs in them.
    ///
    /// This used to require all seven, with at least six packs each and twelve
    /// gaming reticles — written when there were 291 and the risk was a filter
    /// pill leading to a nearly-empty grid. The generated catalog is one pack
    /// now, so the requirement inverts: what matters is that the UI never offers
    /// a filter that leads nowhere.
    #[test]
    fn no_category_filter_leads_to_an_empty_grid() {
        let packs = all();
        for pack in &packs {
            assert!(
                packs.iter().any(|p| p.category == pack.category),
                "{:?} is offered as a filter with nothing behind it",
                pack.category
            );
        }
        assert!(
            packs.iter().any(|p| p.category == Category::Precision),
            "the blend base should stay in Precision, which is what it looks like"
        );
    }

    #[test]
    fn only_the_animated_category_is_animated() {
        for pack in all() {
            assert_eq!(pack.animated, pack.category == Category::Animated, "{}", pack.id);
        }
    }

    #[test]
    fn no_pack_name_borrows_a_third_party_mark() {
        // PRD §15.3. Matching on whole words, not substrings: "mac" inside
        // MACHINED is an ordinary English word, and a check that cannot tell the
        // difference gets weakened or deleted the first time it cries wolf.
        const FORBIDDEN: [&str; 12] = [
            "windows", "microsoft", "mac", "macos", "apple", "amiga", "gameboy", "nintendo",
            "sega", "playstation", "xbox", "valve",
        ];
        const FORBIDDEN_PHRASES: [&str; 2] = ["game boy", "play station"];

        for pack in all() {
            let name = pack.name.to_ascii_lowercase();
            let id = pack.id.to_ascii_lowercase();

            let words: Vec<&str> = name
                .split(|c: char| !c.is_ascii_alphanumeric())
                .chain(id.split(|c: char| !c.is_ascii_alphanumeric()))
                .filter(|w| !w.is_empty())
                .collect();

            for mark in FORBIDDEN {
                assert!(
                    !words.contains(&mark),
                    "{} ({}) borrows the mark \"{mark}\"",
                    pack.name,
                    pack.id
                );
            }
            for phrase in FORBIDDEN_PHRASES {
                assert!(!name.contains(phrase), "{} borrows \"{phrase}\"", pack.name);
            }
        }
    }

    /// The check above must still catch a real borrowing, or it is decoration.
    #[test]
    fn the_trademark_check_would_catch_an_actual_borrowing() {
        let words: Vec<&str> = "retro gameboy"
            .split(|c: char| !c.is_ascii_alphanumeric())
            .filter(|w| !w.is_empty())
            .collect();
        assert!(words.contains(&"gameboy"), "a real mark must still trip it");

        let innocent: Vec<&str> = "machined"
            .split(|c: char| !c.is_ascii_alphanumeric())
            .filter(|w| !w.is_empty())
            .collect();
        assert!(!innocent.contains(&"mac"), "an ordinary word must not trip it");
    }
}
