//! Signature verification for downloaded installers.
//!
//! ## What the checksum does not do
//!
//! `updates::verified_installer` already hashes every download against the
//! `SHA256SUMS.txt` published with the release. That protects against a
//! corrupted or truncated file, and against nothing else — because the checksum
//! comes from the same host as the file it describes. Anyone who can replace one
//! can replace the other, and the app would verify the substitution against
//! itself and run it.
//!
//! A signature closes that, and only a signature can: the private half never
//! leaves the author's machine, so a release path that is entirely compromised
//! still cannot produce a file this build will execute.
//!
//! ## Minisign, and not our own crypto
//!
//! The format is [minisign](https://jedisct1.github.io/minisign/) — Ed25519,
//! one line of public key, a small `.minisig` beside each asset. It is what
//! Tauri's own updater uses, so the signing side is a tool that already exists
//! and is already tested by people who are not us.
//!
//! Verification is [`minisign_verify`], not a hand-rolled Ed25519. Same
//! reasoning as `crate::hash` calling Windows' CNG rather than carrying a SHA-2
//! implementation: a security primitive we wrote is a security primitive we have
//! to review, and this one has no dependencies of its own to review with it.
//!
//! ## Why this can be absent
//!
//! [`public_key`] reads a compile-time environment variable. A build made
//! without it — anyone's local `cargo build`, and every release up to and
//! including v1.20.0 — has no key to check against, and [`enforced`] is false.
//!
//! **That is a deliberate fallback and not a quiet one.** The alternative is a
//! build that refuses every update because it has nothing to verify with, which
//! would turn a missing build-time variable into a fleet that can never be
//! updated again — including out of the state that caused it. The release
//! workflow refuses to publish without the key, which is where that should be
//! enforced: at the point of publishing, once, rather than on every machine
//! afterwards.
//!
//! `docs/SIGNING.md` has the key generation and rotation procedure. The key
//! itself is not in this repository and is not generated by anything in it.

use crate::error::{AppError, AppResult};

/// The public half of the release signing key, stamped in at compile time.
///
/// Set by `scripts/build-release.mjs` and by the release workflow, from the
/// `CURSED_UPDATE_PUBLIC_KEY` secret. A minisign public key is one line and
/// carries no secret, so compiling it into a binary anyone can download costs
/// nothing — that is what a public key is.
pub fn public_key() -> Option<&'static str> {
    normalise(option_env!("CURSED_UPDATE_PUBLIC_KEY"))
}

/// Trims the variable and treats blank as absent.
///
/// An unset GitHub Actions secret arrives as an empty string rather than as
/// nothing, and a pasted key arrives with a trailing newline more often than
/// not. Without this, the first is a key that fails to parse on every update
/// and the second is a build that enforces nothing while reporting that it
/// does.
fn normalise(raw: Option<&'static str>) -> Option<&'static str> {
    raw.map(str::trim).filter(|key| !key.is_empty())
}

/// Whether this build will refuse an installer it cannot verify.
pub fn enforced() -> bool {
    public_key().is_some()
}

/// What to tell the user, and the log, about this build's guarantee.
pub fn describe() -> &'static str {
    if enforced() {
        "downloaded installers are checked against the release signature before they run"
    } else {
        "this build carries no signing key, so downloaded installers are checked against \
         the published checksum only"
    }
}

/// Verifies `bytes` against a minisign signature.
///
/// Fails closed in every direction: a build with no key refuses outright rather
/// than returning success, so a caller that reaches this without checking
/// [`enforced`] first cannot accidentally treat "nothing to check with" as
/// "checked".
pub fn verify(bytes: &[u8], signature: &str) -> AppResult<()> {
    let Some(key_text) = public_key() else {
        return Err(AppError::msg(
            "this build has no signing key compiled in, so it cannot verify a signature",
        ));
    };

    let key = minisign_verify::PublicKey::decode(key_text).map_err(|e| {
        // A malformed key is a build-time mistake, not a user's problem, and it
        // is worth saying so precisely — the alternative is "signature check
        // failed" on every update from a build whose key was pasted with a
        // trailing newline.
        AppError::msg(format!(
            "the signing key compiled into this build is not a valid minisign key: {e}"
        ))
    })?;

    let signature = minisign_verify::Signature::decode(signature)
        .map_err(|e| AppError::msg(format!("the release signature could not be read: {e}")))?;

    key.verify(bytes, &signature, false)
        .map_err(|_| AppError::msg("the installer does not match the release signature"))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The whole design in one assertion: no key means no enforcement, and no
    /// enforcement must never be reachable as a *successful* verification.
    #[test]
    fn a_build_without_a_key_refuses_rather_than_passes() {
        if enforced() {
            return; // a signed build; the assertions below are about the other one
        }
        let refused = verify(b"anything at all", "not a signature");
        assert!(refused.is_err(), "verification without a key must never succeed");
        assert!(!describe().contains("signature"), "{}", describe());
    }

    /// Garbage in the signature slot is refused whatever else is true. Written
    /// so it holds on a signed build as well — there, the key parses and the
    /// signature does not.
    #[test]
    fn nonsense_is_never_a_valid_signature() {
        for attempt in ["", "untrusted comment: x", "\n\n", "RWQ", "0123456789"] {
            assert!(
                verify(b"the installer", attempt).is_err(),
                "{attempt:?} was accepted as a signature"
            );
        }
    }

    /// An empty or whitespace-only variable is the shape a CI secret takes when
    /// it is not set, and it must read as absent rather than as a key that will
    /// fail to parse on every update.
    #[test]
    fn a_blank_key_counts_as_no_key() {
        // Against `normalise` rather than `public_key`, because the environment
        // a test runs in cannot change what was compiled in.
        assert_eq!(normalise(None), None);
        assert_eq!(normalise(Some("")), None);
        assert_eq!(normalise(Some("   ")), None);
        assert_eq!(normalise(Some("\n")), None);
        assert_eq!(normalise(Some(" RWQabc \n")), Some("RWQabc"));
    }

    /// The description is shown to the user in About and written to the log on
    /// every launch, so it has to say which of the two guarantees is in force.
    #[test]
    fn the_description_matches_what_is_enforced() {
        assert_eq!(describe().contains("checksum only"), !enforced());
    }
}
