//! Signature verification for downloaded installers.
//!
//! ## What the checksum does not do
//!
//! `updates::verified_installer` already hashes every download against the
//! `SHA256SUMS.txt` published with the release. That protects against a
//! corrupted or truncated file, and against nothing else — because the checksum
//! comes from the same host as the file it describes. Anyone who can replace one
//! can replace the other, and the app would verify the substitution against
//! itself and run it.
//!
//! A signature closes that, and only a signature can: the private half never
//! leaves the author's machine, so a release path that is entirely compromised
//! still cannot produce a file this build will execute.
//!
//! ## Minisign, and not our own crypto
//!
//! The format is [minisign](https://jedisct1.github.io/minisign/) — Ed25519,
//! one line of public key, a small `.minisig` beside each asset. It is what
//! Tauri's own updater uses, so the signing side is a tool that already exists
//! and is already tested by people who are not us.
//!
//! Verification is [`minisign_verify`], not a hand-rolled Ed25519. Same
//! reasoning as `crate::hash` calling Windows' CNG rather than carrying a SHA-2
//! implementation: a security primitive we wrote is a security primitive we have
//! to review, and this one has no dependencies of its own to review with it.
//!
//! ## Why this can be absent
//!
//! [`public_key`] reads a compile-time environment variable. A build made
//! without it — anyone's local `cargo build`, and every release up to and
//! including v1.20.0 — has no key to check against, and [`enforced`] is false.
//!
//! **That is a deliberate fallback and not a quiet one.** The alternative is a
//! build that refuses every update because it has nothing to verify with, which
//! would turn a missing build-time variable into a fleet that can never be
//! updated again — including out of the state that caused it. The release
//! workflow refuses to publish without the key, which is where that should be
//! enforced: at the point of publishing, once, rather than on every machine
//! afterwards.
//!
//! `docs/SIGNING.md` has the key generation and rotation procedure. The key
//! itself is not in this repository and is not generated by anything in it.

use crate::error::{AppError, AppResult};

/// The public half of the release signing key, stamped in at compile time.
///
/// Set by `scripts/build-release.mjs` and by the release workflow, from the
/// `CURSED_UPDATE_PUBLIC_KEY` secret. A minisign public key is one line and
/// carries no secret, so compiling it into a binary anyone can download costs
/// nothing — that is what a public key is.
pub fn public_key() -> Option<&'static str> {
    normalise(option_env!("CURSED_UPDATE_PUBLIC_KEY"))
}

/// Trims the variable and treats blank as absent.
///
/// An unset GitHub Actions secret arrives as an empty string rather than as
/// nothing, and a pasted key arrives with a trailing newline more often than
/// not. Without this, the first is a key that fails to parse on every update
/// and the second is a build that enforces nothing while reporting that it
/// does.
fn normalise(raw: Option<&'static str>) -> Option<&'static str> {
    raw.map(str::trim).filter(|key| !key.is_empty())
}

/// Whether this build will refuse an installer it cannot verify.
pub fn enforced() -> bool {
    public_key().is_some()
}

/// Reads a minisign public key in any of the three shapes it comes in.
///
/// **All three occur, and two of them are what a person will actually paste.**
///
///  1. The two-line `minisign.pub` file: a comment, then the key. This is the
///     only shape `minisign_verify::PublicKey::decode` accepts.
///  2. The bare key line, `RW…`, which is what most documentation quotes and
///     what somebody copying "the key" out of that file will take.
///  3. **A single-line base64 blob of the whole file**, which is what
///     `tauri signer generate` writes into `<name>.key.pub`.
///
/// The third is the trap. `docs/SIGNING.md` says to put the contents of that
/// file into the secret, so the shape the owner is most likely to paste is the
/// one `decode` cannot read — it would take the whole blob as the comment line,
/// find no second line, and fail. The build would succeed, the release would be
/// signed, and **every update would be refused as tampered**, on every machine,
/// with the only clue in a log file.
///
/// So all three are accepted. Being liberal about the encoding of a public key
/// costs nothing: whatever shape it arrives in, it either decodes to the same
/// 32 bytes or it does not decode at all.
fn parse_public_key(text: &str) -> Option<minisign_verify::PublicKey> {
    let text = text.trim();
    if text.is_empty() {
        return None;
    }

    // 1. The file as minisign writes it.
    if let Ok(key) = minisign_verify::PublicKey::decode(text) {
        return Some(key);
    }
    // 2. Just the key line.
    if let Ok(key) = minisign_verify::PublicKey::from_base64(text) {
        return Some(key);
    }
    // 3. The file, base64'd — Tauri's `.key.pub`. Decoded once, then tried
    //    again as (1) and (2). Not recursive: a base64 blob of a base64 blob is
    //    not a shape any tool produces, and refusing it keeps this bounded.
    let decoded = base64_decode(text)?;
    let decoded = std::str::from_utf8(&decoded).ok()?.trim();
    minisign_verify::PublicKey::decode(decoded)
        .or_else(|_| minisign_verify::PublicKey::from_base64(decoded))
        .ok()
}

/// Standard base64, ignoring whitespace, rejecting anything else.
///
/// Twenty lines rather than a dependency. The only thing it is ever pointed at
/// is a public key that already has to parse as one afterwards, so a bug here
/// fails closed — it cannot turn a wrong key into a right one.
fn base64_decode(text: &str) -> Option<Vec<u8>> {
    const ALPHABET: &[u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    let mut out = Vec::with_capacity(text.len() / 4 * 3);
    let mut buffer = 0u32;
    let mut bits = 0u32;
    for byte in text.bytes() {
        if byte.is_ascii_whitespace() {
            continue;
        }
        if byte == b'=' {
            break;
        }
        let value = ALPHABET.iter().position(|c| *c == byte)? as u32;
        buffer = (buffer << 6) | value;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push((buffer >> bits) as u8);
        }
    }
    Some(out)
}

/// What to tell the user, and the log, about this build's guarantee.
pub fn describe() -> &'static str {
    if enforced() {
        "downloaded installers are checked against the release signature before they run"
    } else {
        "this build carries no signing key, so downloaded installers are checked against \
         the published checksum only"
    }
}

/// Verifies `bytes` against a minisign signature.
///
/// Fails closed in every direction: a build with no key refuses outright rather
/// than returning success, so a caller that reaches this without checking
/// [`enforced`] first cannot accidentally treat "nothing to check with" as
/// "checked".
pub fn verify(bytes: &[u8], signature: &str) -> AppResult<()> {
    let Some(key_text) = public_key() else {
        return Err(AppError::msg(
            "this build has no signing key compiled in, so it cannot verify a signature",
        ));
    };

    let key = parse_public_key(key_text).ok_or_else(|| {
        // A malformed key is a build-time mistake, not a user's problem, and it
        // is worth saying so precisely — the alternative is "signature check
        // failed" on every update from a build whose key was pasted in the
        // wrong shape.
        AppError::msg("the signing key compiled into this build is not a valid minisign key")
    })?;

    let signature = minisign_verify::Signature::decode(signature)
        .map_err(|e| AppError::msg(format!("the release signature could not be read: {e}")))?;

    key.verify(bytes, &signature, false)
        .map_err(|_| AppError::msg("the installer does not match the release signature"))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A throwaway key pair, generated once for these tests and used nowhere
    /// else. Its private half was never committed and no longer exists.
    ///
    /// In the shape `tauri signer generate` writes it: **the whole file,
    /// base64'd onto one line.** That is the shape the owner pastes into the
    /// secret, so it is the shape the test has to use — a fixture in the
    /// convenient shape would pass while the real thing failed.
    const TEST_KEY: &str = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IERGOUU2\
                            ODUxMEFGNEI0QTkKUldTcHRQUUtVV2llM3dzK3JYN1V4VldNZXgxZGpkaFc5\
                            eTV4LzhqWXd3SWFiV0MrNmJxd2t1YlEK";

    /// Produced by running `scripts/sign-release.mjs` over `TEST_PAYLOAD` with
    /// the matching private key. Not hand-written: this is the script's actual
    /// output, unwrapped from Tauri's extra base64 layer exactly as it will be
    /// on a release.
    const TEST_SIGNATURE: &str = "untrusted comment: signature from tauri secret key\n\
        RUSptPQKUWie3yQCtdMxtIEOfWl67APgQ7zsvjJV/ITQZBrPH+VhpnpgBLSbnjglgn3QIFHhGn5UvpFovwu7dn1gExm2vQHfWQM=\n\
        trusted comment: timestamp:1786913886\tfile:Cursed_9.9.9_x64-setup.exe\n\
        hXXgjMO1bCUNacFob30uZz5P+WCtr3kAiCrgzfoHeqA3GWkQd0pQk803kWnH284zJqFBuDX4L0+O8803RC+pDg==\n";

    const TEST_PAYLOAD: &[u8] = b"cursed-signature-fixture";

    /// **The end-to-end test.** A signature this project's own script produced,
    /// against a key in the shape its own documentation tells you to paste,
    /// verified by the code that gates an update.
    ///
    /// Written after the first release attempt, which failed for two reasons
    /// neither of which any test could see: the signing script could not spawn
    /// the CLI, and the key shape it produces is one `PublicKey::decode`
    /// refuses. Both were invisible until a real build ran.
    #[test]
    fn a_signature_from_the_release_script_verifies() {
        let key = parse_public_key(TEST_KEY).expect("the key shape tauri writes must parse");
        let signature =
            minisign_verify::Signature::decode(TEST_SIGNATURE).expect("the signature must parse");
        key.verify(TEST_PAYLOAD, &signature, false)
            .expect("a genuine signature must verify");
    }

    /// And the same signature against different bytes must not.
    #[test]
    fn a_signature_does_not_verify_against_other_bytes() {
        let key = parse_public_key(TEST_KEY).expect("key");
        let signature = minisign_verify::Signature::decode(TEST_SIGNATURE).expect("signature");
        assert!(
            key.verify(b"a different installer", &signature, false).is_err(),
            "a signature that verifies anything verifies nothing"
        );
    }

    /// All three shapes a public key arrives in have to work, because two of
    /// them are what a person actually pastes.
    #[test]
    fn every_shape_of_public_key_is_accepted() {
        let file = String::from_utf8(base64_decode(TEST_KEY).expect("decodes")).expect("utf8");
        let bare = file.lines().nth(1).expect("key line").to_owned();
        let padded = format!("  {bare}\n");

        // Compared by what they *do*, not by struct equality. A bare key line
        // carries no comment and the two-line file does, so the structs
        // legitimately differ in a field that has nothing to do with identity —
        // asserting on it would be asserting on a cosmetic difference and
        // failing for the wrong reason, which is exactly what it did.
        let signature =
            minisign_verify::Signature::decode(TEST_SIGNATURE).expect("the signature must parse");

        for (shape, text) in [
            ("tauri's base64 file", TEST_KEY),
            ("the minisign.pub file", file.as_str()),
            ("the bare key line", bare.as_str()),
            ("a key pasted with whitespace", padded.as_str()),
        ] {
            let key = parse_public_key(text).unwrap_or_else(|| panic!("{shape} did not parse"));
            key.verify(TEST_PAYLOAD, &signature, false)
                .unwrap_or_else(|_| panic!("{shape} parsed but did not verify"));
        }
    }

    #[test]
    fn nonsense_is_not_a_public_key() {
        for bad in ["", "   ", "not a key", "RW", "!!!!", "dGhpcyBpcyBub3QgYSBrZXk="] {
            assert!(parse_public_key(bad).is_none(), "{bad:?} was accepted");
        }
    }

    #[test]
    fn base64_matches_the_published_test_vectors() {
        assert_eq!(base64_decode("").unwrap(), b"");
        assert_eq!(base64_decode("Zg==").unwrap(), b"f");
        assert_eq!(base64_decode("Zm8=").unwrap(), b"fo");
        assert_eq!(base64_decode("Zm9v").unwrap(), b"foo");
        assert_eq!(base64_decode("Zm9vYmFy").unwrap(), b"foobar");
        // Whitespace is skipped; anything else is refused.
        assert_eq!(base64_decode("Zm9v\n YmFy").unwrap(), b"foobar");
        assert!(base64_decode("Zm9v*YmFy").is_none());
    }

    /// The whole design in one assertion: no key means no enforcement, and no
    /// enforcement must never be reachable as a *successful* verification.
    #[test]
    fn a_build_without_a_key_refuses_rather_than_passes() {
        if enforced() {
            return; // a signed build; the assertions below are about the other one
        }
        let refused = verify(b"anything at all", "not a signature");
        assert!(refused.is_err(), "verification without a key must never succeed");
        assert!(!describe().contains("signature"), "{}", describe());
    }

    /// Garbage in the signature slot is refused whatever else is true. Written
    /// so it holds on a signed build as well — there, the key parses and the
    /// signature does not.
    #[test]
    fn nonsense_is_never_a_valid_signature() {
        for attempt in ["", "untrusted comment: x", "\n\n", "RWQ", "0123456789"] {
            assert!(
                verify(b"the installer", attempt).is_err(),
                "{attempt:?} was accepted as a signature"
            );
        }
    }

    /// An empty or whitespace-only variable is the shape a CI secret takes when
    /// it is not set, and it must read as absent rather than as a key that will
    /// fail to parse on every update.
    #[test]
    fn a_blank_key_counts_as_no_key() {
        // Against `normalise` rather than `public_key`, because the environment
        // a test runs in cannot change what was compiled in.
        assert_eq!(normalise(None), None);
        assert_eq!(normalise(Some("")), None);
        assert_eq!(normalise(Some("   ")), None);
        assert_eq!(normalise(Some("\n")), None);
        assert_eq!(normalise(Some(" RWQabc \n")), Some("RWQabc"));
    }

    /// The description is shown to the user in About and written to the log on
    /// every launch, so it has to say which of the two guarantees is in force.
    #[test]
    fn the_description_matches_what_is_enforced() {
        assert_eq!(describe().contains("checksum only"), !enforced());
    }
}
